"""create posts and deleted_posts table

Revision ID: 2b707be1442b
Revises: 
Create Date: 2023-03-02 08:50:50.681605+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b707be1442b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deleted_posts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("note", "article", "like", "bookmark", "repost", name="postkind"),
            nullable=False,
        ),
        sa.Column("published", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("note", "article", "like", "bookmark", "repost", name="postkind"),
            nullable=False,
        ),
        sa.Column("published", sa.DateTime(), nullable=False),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("(NULL)"), nullable=True
        ),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.drop_table("deleted_posts")
    # ### end Alembic commands ###
